apiVersion: beyond.soleaenergy.com/v1
kind: BeyondFunction
metadata:
  name: forward-auth-test
spec:
  env:
    name: forward-auth-test
    image:
      builder: harbor.corp.soleaenergy.com/library/solea-go-builder:1.21.2
      runtime: harbor.corp.soleaenergy.com/library/solea-go-env:1.21.2
    poolSize: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 1
      limits:
        memory: 512Mi
        cpu: 2
  functions:
    - name: forward-auth-test
      entrypoint: Handler
      env: forward-auth-test
      pkg: forward-auth-test
      secrets:
        - name: beyond
          namespace: beyond-dev
      triggers:
        http:
          - name: forward-auth
            methods:
              - POST
            routeHost: ldev-beyond.soleaenergy.com
            prefix: /int/function/forward-auth/
  git:
    repository:
      account: SoleaEnergy
      name: forward-auth-test
      branch: dev
  package:
    name: forward-auth-test
    env: forward-auth-test
    script: pkg.sh
    source: fn.zip
  secretName: beyond # secrets deployed by the operator will have the "kind" prefix (e.g. beyondsecret-name)